ALTER TABLE PUBLIC.LATENESS_SOURCE_DATA  ADD COLUMN GTT_TRIP_ID TEXT;

ALTER TABLE PUBLIC.LATENESS_SOURCE_DATA  ADD COLUMN STOPSTARTID TEXT;

ALTER TABLE PUBLIC.LATENESS_SOURCE_DATA  ADD COLUMN STOPENDID TEXT;
