-- Create external analytics schema
CREATE EXTERNAL SCHEMA IF NOT EXISTS ext_analytics
FROM DATA CATALOG
DATABASE '{GLUE_ANALYTICS_DB}'
IAM_ROLE '{IAM_ROLE}'
CREATE EXTERNAL DATABASE IF NOT EXISTS;

-- Create external TSP schema
CREATE EXTERNAL SCHEMA IF NOT EXISTS ext_tsp
FROM DATA CATALOG
DATABASE '{GLUE_TSP_DB}'
IAM_ROLE '{IAM_ROLE}'
CREATE EXTERNAL DATABASE IF NOT EXISTS;

-- Create external GTFS schema
CREATE EXTERNAL SCHEMA IF NOT EXISTS ext_gtfs 
FROM DATA CATALOG
DATABASE '{GLUE_GTFS_DB}'
IAM_ROLE '{IAM_ROLE}'
CREATE EXTERNAL DATABASE IF NOT EXISTS;

-- Create external EVP schema
CREATE EXTERNAL SCHEMA IF NOT EXISTS ext_evp 
FROM DATA CATALOG
DATABASE '{GLUE_EVP_DB}'
IAM_ROLE '{IAM_ROLE}'
CREATE EXTERNAL DATABASE IF NOT EXISTS;
