CREATE TABLE IF NOT EXISTS evp.evp_intersections (
  "name" TEXT,
  location_id TEXT,
  latitude TEXT,
  longitude TEXT,
  cabinaet TEXT,
  controller TEXT,
  int_number TEXT,
  controller_lan_ip TEXT,
  make TEXT,
  model TEXT,
  signal_core_serial_number TEXT,
  serial_number_764 TEXT,
  lan_ip TEXT,
  miovision_id TEXT,
  configured_764 TEXT,
  approach_threshold_adjusted TEXT,
  notes TEXT,
  agency_id TEXT,
  utc_date TEXT
)