AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: CDF Device Credentials


Parameters:

  BucketName:
    Description: Name of bucket to store command information.
    Type: String
    MinLength: 1

Resources:

  S3DeviceAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: credentials.iot.amazonaws.com
          Action: sts:AssumeRole
      Path: "/cdf/"
      ManagedPolicyArns:
        - !Ref S3DeviceAccessRolePolicy

  S3DeviceAccessRolePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: 'cdf S3 device access'
      Path: "/cdf/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "s3:Put*"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"


Outputs:
  S3DeviceAccessRoleName:
    Description: S3 Device Access Role Name
    Value: !Ref S3DeviceAccessRole
    Export: 
      Name: !Sub "${AWS::StackName}-S3DeviceAccessRoleName"
  S3DeviceAccessRoleArn:
    Description: S3 Device Access Role Arn
    Value: !GetAtt S3DeviceAccessRole.Arn
    Export: 
      Name: !Sub "${AWS::StackName}-S3DeviceAccessRoleArn"
