version: "3"

services:
  jupyter:
    image: jupyter/pyspark-notebook
    volumes:
      - "${PWD}:/home/jovyan/work"
    ports:
      - 8888:8888
    command: bash -c "
      printf 'Open http://localhost:8888\n\n'
      && start.sh jupyter notebook --NotebookApp.token='' 2> /dev/null
      "
